name: mood_diary_ui
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_gen_runner: ^5.6.0
  flutter_localization: ^0.2.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  intl: ^0.18.1

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-Bold.ttf          
        - asset: assets/fonts/Nunito-Italic.ttf
          style: italic

flutter_gen:
  output: lib/core/generated/

  integrations:
    flutter_svg: true
